"""Typed physical components and versioned component catalogs."""

from .grammar import (
    GRAMMAR_VERSION,
    GrammarViolation,
    Material,
    MountingPlateSpec,
)
from .part_contract import (
    INTERFACE_TYPES,
    PART_CONTRACT_VERSION,
    PartContract,
    PartContractViolation,
    canonical_part_bytes,
    part_declaration_sha256,
    validate_part_mapping,
)
from .brep_grammar import (
    BREP_GRAMMAR_VERSION,
    OPERATORS as BREP_OPERATORS,
    BrepGrammarViolation,
    brep_declaration_sha256,
    validate_brep_grammar,
)
from .engineering_contracts import (
    GEOMETRY_WITNESS_VERSION,
    MANUFACTURING_CONTRACT_VERSION,
    MATERIAL_CONTRACT_VERSION,
    EngineeringContractViolation,
    evaluate_manufacturing_witness,
    record_sha256,
    validate_engineering_assignment,
    validate_manufacturing_process,
    validate_material_record,
)
from .freeform_wire_grammar import (
    CONSTRAINTS as FREEFORM_WIRE_CONSTRAINTS,
    GRAMMAR_VERSION as FREEFORM_WIRE_GRAMMAR_VERSION,
    OPERATORS as FREEFORM_WIRE_OPERATORS,
    TRANSFORMS as FREEFORM_WIRE_TRANSFORMS,
    FreeformWireGrammarError,
    compare_measurement_witnesses,
    declaration_sha256 as freeform_wire_declaration_sha256,
    validate_grammar as validate_freeform_wire_grammar,
)
from .freeform_solid_grammar import (
    DATUM_KINDS as FREEFORM_SOLID_DATUM_KINDS,
    GRAMMAR_VERSION as FREEFORM_SOLID_GRAMMAR_VERSION,
    OPERATORS as FREEFORM_SOLID_OPERATORS,
    REQUIRED_FAMILIES as FREEFORM_SOLID_REQUIRED_FAMILIES,
    FreeformSolidGrammarError,
    declaration_sha256 as freeform_solid_declaration_sha256,
    validate_solid_grammar,
)
from .constructive_validity import (
    GATE_VERSION as CONSTRUCTIVE_VALIDITY_GATE_VERSION,
    REPAIR_OPERATIONS as CONSTRUCTIVE_REPAIR_OPERATIONS,
    ConstructiveValidityError,
    build_candidate as build_constructive_candidate,
    evaluate_candidate as evaluate_constructive_candidate,
    validate_gate_config as validate_constructive_gate_config,
)
from .semantic_geometry_witness import (
    WITNESS_VERSION as SEMANTIC_GEOMETRY_WITNESS_VERSION,
    SemanticWitnessViolation,
    compare_report as compare_semantic_geometry_report,
    validate_config as validate_semantic_geometry_config,
)

__all__ = [
    "GRAMMAR_VERSION",
    "GrammarViolation",
    "Material",
    "MountingPlateSpec",
    "INTERFACE_TYPES",
    "PART_CONTRACT_VERSION",
    "PartContract",
    "PartContractViolation",
    "canonical_part_bytes",
    "part_declaration_sha256",
    "validate_part_mapping",
    "BREP_GRAMMAR_VERSION",
    "BREP_OPERATORS",
    "BrepGrammarViolation",
    "brep_declaration_sha256",
    "validate_brep_grammar",
    "GEOMETRY_WITNESS_VERSION",
    "MANUFACTURING_CONTRACT_VERSION",
    "MATERIAL_CONTRACT_VERSION",
    "EngineeringContractViolation",
    "evaluate_manufacturing_witness",
    "record_sha256",
    "validate_engineering_assignment",
    "validate_manufacturing_process",
    "validate_material_record",
    "FREEFORM_WIRE_CONSTRAINTS",
    "FREEFORM_WIRE_GRAMMAR_VERSION",
    "FREEFORM_WIRE_OPERATORS",
    "FREEFORM_WIRE_TRANSFORMS",
    "FreeformWireGrammarError",
    "compare_measurement_witnesses",
    "freeform_wire_declaration_sha256",
    "validate_freeform_wire_grammar",
    "FREEFORM_SOLID_DATUM_KINDS",
    "FREEFORM_SOLID_GRAMMAR_VERSION",
    "FREEFORM_SOLID_OPERATORS",
    "FREEFORM_SOLID_REQUIRED_FAMILIES",
    "FreeformSolidGrammarError",
    "freeform_solid_declaration_sha256",
    "validate_solid_grammar",
    "CONSTRUCTIVE_VALIDITY_GATE_VERSION",
    "CONSTRUCTIVE_REPAIR_OPERATIONS",
    "ConstructiveValidityError",
    "build_constructive_candidate",
    "evaluate_constructive_candidate",
    "validate_constructive_gate_config",
    "SEMANTIC_GEOMETRY_WITNESS_VERSION",
    "SemanticWitnessViolation",
    "compare_semantic_geometry_report",
    "validate_semantic_geometry_config",
]
