"""Race execution and multi-fidelity orchestration."""

from .coupling import (
    COUPLING_STAGES,
    EVENT_PRIORITY,
    RESIDUAL_UNITS,
    ArtifactReference,
    CompiledCouplingArchitecture,
    ComponentHealthState,
    ContactRuntimeState,
    CoupledModuleSpec,
    CouplingContractError,
    EventCandidate,
    EventDecision,
    ExperimentManifest,
    ResidualEntry,
    ResidualLedger,
    SharedVehicleState,
    VersionPin,
    arbitrate_event_candidates,
    compile_coupling_architecture,
    load_coupling_architecture,
)
from .transaction import (
    AdapterOutput,
    AdapterReadView,
    AdapterTrace,
    CoupledAdapter,
    CoupledStepResult,
    CoupledTransactionError,
    FunctionCoupledAdapter,
    RuntimeSignal,
    TransactionFailure,
    execute_coupled_step,
)

__all__ = [
    "COUPLING_STAGES",
    "EVENT_PRIORITY",
    "RESIDUAL_UNITS",
    "ArtifactReference",
    "CompiledCouplingArchitecture",
    "ComponentHealthState",
    "ContactRuntimeState",
    "CoupledModuleSpec",
    "CouplingContractError",
    "EventCandidate",
    "EventDecision",
    "ExperimentManifest",
    "ResidualEntry",
    "ResidualLedger",
    "SharedVehicleState",
    "VersionPin",
    "arbitrate_event_candidates",
    "compile_coupling_architecture",
    "load_coupling_architecture",
    "AdapterOutput",
    "AdapterReadView",
    "AdapterTrace",
    "CoupledAdapter",
    "CoupledStepResult",
    "CoupledTransactionError",
    "FunctionCoupledAdapter",
    "RuntimeSignal",
    "TransactionFailure",
    "execute_coupled_step",
]
