"""Race execution and multi-fidelity orchestration."""

from .coupling import (
    COUPLING_STAGES,
    EVENT_PRIORITY,
    RESIDUAL_UNITS,
    ArtifactReference,
    CompiledCouplingArchitecture,
    ComponentHealthState,
    ContactRuntimeState,
    CoupledModuleSpec,
    CouplingContractError,
    EventCandidate,
    EventDecision,
    ExperimentManifest,
    ResidualEntry,
    ResidualLedger,
    SharedVehicleState,
    VersionPin,
    arbitrate_event_candidates,
    compile_coupling_architecture,
    load_coupling_architecture,
)
from .transaction import (
    AdapterOutput,
    AdapterReadView,
    AdapterTrace,
    CoupledAdapter,
    CoupledStepResult,
    CoupledTransactionError,
    FunctionCoupledAdapter,
    RuntimeSignal,
    TransactionFailure,
    execute_coupled_step,
)
from .step_inputs import (
    CircuitEnvironmentInputAdapter,
    CircuitInputScenario,
    EnvironmentStepInputs,
    SpatialStepEvidence,
    StepInputError,
    StepInputResolution,
    StrategyStepCommand,
    TrafficStepEvidence,
    WeatherStepEvidence,
    resolve_step_inputs,
)
from .aero_load_coupling import (
    AeroLoadBalanceResiduals,
    AeroLoadCouplingError,
    AeroLoadCouplingResult,
    AerodynamicChassisWrench,
    AerodynamicCoolingEvidence,
    AerodynamicMapAdapter,
    AerodynamicQueryEvidence,
    AerodynamicReferenceOrigin,
    ContactNormalLoad,
    NormalLoadCouplingAdapter,
    couple_wrench_to_normal_loads,
    moist_air_density_kg_per_m3,
    translate_aerodynamic_result,
)
from .contact_coupling import (
    CONTACT_ADAPTER_VERSION, ContactCouplingConfig, ContactCouplingError,
    ContactCouplingSpec, ContactEnergyTransfer, ContactEnergyTransfers,
    ContactForceMoment, ContactHealthInput, ContactHealthInputs,
    ContactLimitCouplingAdapter, ContactSubsystemSnapshot, CoupledContactForce,
    couple_contacts,
)

__all__ = [
    "COUPLING_STAGES",
    "EVENT_PRIORITY",
    "RESIDUAL_UNITS",
    "ArtifactReference",
    "CompiledCouplingArchitecture",
    "ComponentHealthState",
    "ContactRuntimeState",
    "CoupledModuleSpec",
    "CouplingContractError",
    "EventCandidate",
    "EventDecision",
    "ExperimentManifest",
    "ResidualEntry",
    "ResidualLedger",
    "SharedVehicleState",
    "VersionPin",
    "arbitrate_event_candidates",
    "compile_coupling_architecture",
    "load_coupling_architecture",
    "AdapterOutput",
    "AdapterReadView",
    "AdapterTrace",
    "CoupledAdapter",
    "CoupledStepResult",
    "CoupledTransactionError",
    "FunctionCoupledAdapter",
    "RuntimeSignal",
    "TransactionFailure",
    "execute_coupled_step",
    "CircuitEnvironmentInputAdapter",
    "CircuitInputScenario",
    "EnvironmentStepInputs",
    "SpatialStepEvidence",
    "StepInputError",
    "StepInputResolution",
    "StrategyStepCommand",
    "TrafficStepEvidence",
    "WeatherStepEvidence",
    "resolve_step_inputs",
    "AeroLoadBalanceResiduals",
    "AeroLoadCouplingError",
    "AeroLoadCouplingResult",
    "AerodynamicChassisWrench",
    "AerodynamicCoolingEvidence",
    "AerodynamicMapAdapter",
    "AerodynamicQueryEvidence",
    "AerodynamicReferenceOrigin",
    "ContactNormalLoad",
    "NormalLoadCouplingAdapter",
    "couple_wrench_to_normal_loads",
    "moist_air_density_kg_per_m3",
    "translate_aerodynamic_result",
    "CONTACT_ADAPTER_VERSION", "ContactCouplingConfig", "ContactCouplingError",
    "ContactCouplingSpec", "ContactEnergyTransfer", "ContactEnergyTransfers",
    "ContactForceMoment", "ContactHealthInput", "ContactHealthInputs",
    "ContactLimitCouplingAdapter", "ContactSubsystemSnapshot", "CoupledContactForce",
    "couple_contacts",
]
