"""Race execution and multi-fidelity orchestration."""

from .coupling import (
    COUPLING_STAGES,
    EVENT_PRIORITY,
    RESIDUAL_UNITS,
    ArtifactReference,
    CompiledCouplingArchitecture,
    ComponentHealthState,
    ContactRuntimeState,
    CoupledModuleSpec,
    CouplingContractError,
    EventCandidate,
    EventDecision,
    ExperimentManifest,
    ResidualEntry,
    ResidualLedger,
    SharedVehicleState,
    VersionPin,
    arbitrate_event_candidates,
    compile_coupling_architecture,
    load_coupling_architecture,
)
from .transaction import (
    AdapterOutput,
    AdapterReadView,
    AdapterTrace,
    CoupledAdapter,
    CoupledStepResult,
    CoupledTransactionError,
    FunctionCoupledAdapter,
    RuntimeSignal,
    TransactionFailure,
    execute_coupled_step,
)
from .step_inputs import (
    CircuitEnvironmentInputAdapter,
    CircuitInputScenario,
    EnvironmentStepInputs,
    SpatialStepEvidence,
    StepInputError,
    StepInputResolution,
    StrategyStepCommand,
    TrafficStepEvidence,
    WeatherStepEvidence,
    resolve_step_inputs,
)
from .aero_load_coupling import (
    AeroLoadBalanceResiduals,
    AeroLoadCouplingError,
    AeroLoadCouplingResult,
    AerodynamicChassisWrench,
    AerodynamicCoolingEvidence,
    AerodynamicMapAdapter,
    AerodynamicQueryEvidence,
    AerodynamicReferenceOrigin,
    ContactNormalLoad,
    NormalLoadCouplingAdapter,
    couple_wrench_to_normal_loads,
    moist_air_density_kg_per_m3,
    translate_aerodynamic_result,
)
from .contact_coupling import (
    CONTACT_ADAPTER_VERSION, ContactCouplingConfig, ContactCouplingError,
    ContactCouplingSpec, ContactEnergyTransfer, ContactEnergyTransfers,
    ContactForceMoment, ContactHealthInput, ContactHealthInputs,
    ContactLimitCouplingAdapter, ContactSubsystemSnapshot, CoupledContactForce,
    couple_contacts, subsystem_snapshots_from_shared_state,
)
from .motion_coupling import (
    MOTION_ADAPTER_VERSION,
    MotionConfiguration,
    MotionCorridorEvidence,
    MotionCorridorReference,
    MotionCouplingError,
    MotionIntegrationEvidence,
    MotionStepResult,
    VehicleMotionCouplingAdapter,
    integrate_coupled_motion,
)
from .energy_health_coupling import (
    ENERGY_ADAPTER_VERSION,
    HEALTH_ADAPTER_VERSION,
    CentralEnergyAuditAdapter,
    CentralEnergyConfiguration,
    CentralEnergyEvidence,
    CentralEnergyStepResult,
    CentralHealthConfiguration,
    CentralHealthEventAdapter,
    CentralHealthEvidence,
    CentralHealthStepResult,
    ComponentHealthConfiguration,
    ComponentHealthEvidence,
    EnergyHealthCouplingError,
    evaluate_central_energy,
    evaluate_central_health,
)
from .whole_race import (
    RACE_PROGRESS_ADAPTER_VERSION,
    CoupledRaceReplayMetadata,
    CoupledRaceStepTelemetry,
    RaceProgressAdapter,
    RaceProgressConfiguration,
    RaceProgressEvidence,
    RaceProgressStepResult,
    WholeRaceConfiguration,
    WholeRaceError,
    WholeRaceResult,
    merge_race_progress,
    run_whole_race,
)

__all__ = [
    "COUPLING_STAGES",
    "EVENT_PRIORITY",
    "RESIDUAL_UNITS",
    "ArtifactReference",
    "CompiledCouplingArchitecture",
    "ComponentHealthState",
    "ContactRuntimeState",
    "CoupledModuleSpec",
    "CouplingContractError",
    "EventCandidate",
    "EventDecision",
    "ExperimentManifest",
    "ResidualEntry",
    "ResidualLedger",
    "SharedVehicleState",
    "VersionPin",
    "arbitrate_event_candidates",
    "compile_coupling_architecture",
    "load_coupling_architecture",
    "AdapterOutput",
    "AdapterReadView",
    "AdapterTrace",
    "CoupledAdapter",
    "CoupledStepResult",
    "CoupledTransactionError",
    "FunctionCoupledAdapter",
    "RuntimeSignal",
    "TransactionFailure",
    "execute_coupled_step",
    "CircuitEnvironmentInputAdapter",
    "CircuitInputScenario",
    "EnvironmentStepInputs",
    "SpatialStepEvidence",
    "StepInputError",
    "StepInputResolution",
    "StrategyStepCommand",
    "TrafficStepEvidence",
    "WeatherStepEvidence",
    "resolve_step_inputs",
    "AeroLoadBalanceResiduals",
    "AeroLoadCouplingError",
    "AeroLoadCouplingResult",
    "AerodynamicChassisWrench",
    "AerodynamicCoolingEvidence",
    "AerodynamicMapAdapter",
    "AerodynamicQueryEvidence",
    "AerodynamicReferenceOrigin",
    "ContactNormalLoad",
    "NormalLoadCouplingAdapter",
    "couple_wrench_to_normal_loads",
    "moist_air_density_kg_per_m3",
    "translate_aerodynamic_result",
    "CONTACT_ADAPTER_VERSION", "ContactCouplingConfig", "ContactCouplingError",
    "ContactCouplingSpec", "ContactEnergyTransfer", "ContactEnergyTransfers",
    "ContactForceMoment", "ContactHealthInput", "ContactHealthInputs",
    "ContactLimitCouplingAdapter", "ContactSubsystemSnapshot", "CoupledContactForce",
    "couple_contacts",
    "subsystem_snapshots_from_shared_state",
    "MOTION_ADAPTER_VERSION",
    "MotionConfiguration",
    "MotionCorridorEvidence",
    "MotionCorridorReference",
    "MotionCouplingError",
    "MotionIntegrationEvidence",
    "MotionStepResult",
    "VehicleMotionCouplingAdapter",
    "integrate_coupled_motion",
    "ENERGY_ADAPTER_VERSION",
    "HEALTH_ADAPTER_VERSION",
    "CentralEnergyAuditAdapter",
    "CentralEnergyConfiguration",
    "CentralEnergyEvidence",
    "CentralEnergyStepResult",
    "CentralHealthConfiguration",
    "CentralHealthEventAdapter",
    "CentralHealthEvidence",
    "CentralHealthStepResult",
    "ComponentHealthConfiguration",
    "ComponentHealthEvidence",
    "EnergyHealthCouplingError",
    "evaluate_central_energy",
    "evaluate_central_health",
    "RACE_PROGRESS_ADAPTER_VERSION",
    "CoupledRaceReplayMetadata",
    "CoupledRaceStepTelemetry",
    "RaceProgressAdapter",
    "RaceProgressConfiguration",
    "RaceProgressEvidence",
    "RaceProgressStepResult",
    "WholeRaceConfiguration",
    "WholeRaceError",
    "WholeRaceResult",
    "merge_race_progress",
    "run_whole_race",
]
